### PR TITLE
Cleaned up code

### PR DESCRIPTION
**Pull request by supernova350**

### CODE REVIEW

**Comment by supernova350** [comment]
I do not have the time to format the rest, so I would like someone else to. Following the same async/await pattern would be a good idea.

**Comment by MassiGy** [comment]
Hey @supernova350, 

You did a really good job refactoring and cleaning up the code. I like how you escape the callback hell with async/await.
I will also try to do more of that.

Thanks.
Massiles.

**Comment by MassiGy** [comment]
I've just cloned your git repo @supernova350, and I see that you've changed the jobs code a bit. Did you test it ?

Thanks.
Massiles.

**Comment by supernova350** [comment]
I am 99% sure that the accountCleanup job is working. @MassiGy

**Comment by MassiGy** [comment]
Okey, that is fair enough. I will retest it when @William-McGonagle  or @NeilChaudhari  merge the remaining PRs.

Massiles.

**Review by William-McGonagle — CHANGES_REQUESTED** [review]
Looks good- can you add the Prettierrc file back in. I removed it because I thought it was supposed to be in the gitignore at first. 😬

**Comment by MassiGy** [comment]
Hey there @William-McGonagle,

Yeah no problem, I am currently working on this PR. I'am fixing the merge conflicts and in my current version of code I still have the Prettierrc file.

I will submit a new PR soon, which will be the fixed version of this one, thanks again to @supernova350.

Hope that was clear.
Massiles.

**Comment by MassiGy** [comment]
Hey everyone.

I will close this one since the PR #119  wraps it, and solve the current merge conflicts.

Hope that is clear.
Massiles.

**Comment by MassiGy** [comment]
Hey everyone.

I will close this one since the PR #119  wraps it, and solve the current merge conflicts.

Hope that is clear.
Massiles.

**Pull request closed without merging**
